apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSFJ0SU5JcE4xTGd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU16RXdPREEyTXpSYUZ3MHpOakExTWpnd09ERXhNelJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNvY2dVdzZYdHpCSTJXTHZDV2NEQ3JDb3J3TDZiT2diQm8vTU92UmcvMEoxWElCSzkwSVR5Rk9pNkQKb3ZmVXh6Q3B0WjVDYlI3WFJVR01LSTdHVGt3OVpQZ1RHejRmNEhzaW4rWTdtOWVQUFNsRUUwT0FBajBLbnhjcQo0TUtWWHNPNkc3YXhRd0RqcHJqSllwZmIwYUJvWkRycDBUSjVHMkRIQkhYNTl0aUZFWThqd01QakNFd0RJWlVjCjM4Nm13NzJzTzArY2FWVmd1TzRSRXZJRnV5QUE1K3FPdW5nWjJpRmlCbUdFMWk0MTZNMVFTUituemdVNjlDaEcKaTNSRUNpNVN0WnFEMHdETkJNT1dRZzB6LzcxNlF2L1AxOHFocWJ3N1NaY0c1bzdiY3puL01yN1UyUmxDaDBuNwo4amFwUXF6bXJIQVVGN01WbHA1WitzemFvMTZSQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSZlNqYno4eGJVWkJQazZWYWZrMWVxTG5sZGd6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTZhUHJSdVJSaApCYzZpYUd1U2lHUVhUSkNCSE9tK1QvekNOdTNVVFAxUmltSjNWdTEyYWU4K2s4YW5EeDJiQlYrUnkwWWdEVitVCkRZd0pVSEIxZEluekZNcGEvSVR5ekFOS1lGU212Tk9VUFNJcitqa3MwZHNLek1Xdy84YnhlblJSdFI0WVZKNWoKdG9nTng4NFIwSTdVWGZXYjRJeGtxeXIvdHZFY0UwRDNlaExtcHlsK29OVElSSkE3Zlc5Qkkzb1d5bzNSOWZCZAp3Ynh2WlZON2ZTcnAvdFVETE1OanBOSnF0YW5MalNQK1d4YW1WT1ZSTkhUZ2xYTWtQV2tnN1Vud3kwSUlPanV4CkJyNFBjMEZWUUt4ODcrcTljbDNWYjNzaVpHWlAyZlRvaTVuOWhzdm1EekpmNTZMNEUrbUR6MlpaTTQ5Wkg3YzEKSHptTU1qL3BnbXZlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://230203CE37303297DE60AABE4785EA58.gr7.us-east-1.eks.amazonaws.com
  name: clus-ltrobs-2001-event
contexts:
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-01
    user: workshop-students
  name: student-01
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-02
    user: workshop-students
  name: student-02
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-03
    user: workshop-students
  name: student-03
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-04
    user: workshop-students
  name: student-04
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-05
    user: workshop-students
  name: student-05
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-06
    user: workshop-students
  name: student-06
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-07
    user: workshop-students
  name: student-07
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-08
    user: workshop-students
  name: student-08
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-09
    user: workshop-students
  name: student-09
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-10
    user: workshop-students
  name: student-10
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-11
    user: workshop-students
  name: student-11
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-12
    user: workshop-students
  name: student-12
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-13
    user: workshop-students
  name: student-13
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-14
    user: workshop-students
  name: student-14
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-15
    user: workshop-students
  name: student-15
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-16
    user: workshop-students
  name: student-16
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-17
    user: workshop-students
  name: student-17
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-18
    user: workshop-students
  name: student-18
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-19
    user: workshop-students
  name: student-19
- context:
    cluster: clus-ltrobs-2001-event
    namespace: student-20
    user: workshop-students
  name: student-20
current-context: student-01
kind: Config
preferences: {}
users:
- name: workshop-students
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJ5NkhZTmlxemw5ZTgxUXg5Y01ja2tEYmE0SlVodjI5ZEFQa0NvV09XV3cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ3b3Jrc2hvcC1hY2Nlc3MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoid29ya3Nob3Atc3R1ZGVudHMtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoid29ya3Nob3Atc3R1ZGVudHMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI2M2M4YjQxZC0yZWVhLTQyODAtYTVmYi0yNWZhNjY3MDAwMGUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6d29ya3Nob3AtYWNjZXNzOndvcmtzaG9wLXN0dWRlbnRzIn0.cVIF9v4wBPO3JYEVVq4tw_uz2cRjr6lGsVteDz7ZWMjCO8jALAjLWnaBF9vl1_sV4UA56xnR-WtQxDIDPUiUis24PqWu59c8e8Id1s7bwwEwpYwoUcaQY8uwwvf5ttTgn46pl5b_HEbOVL_Z4U5qbked-YU3gVfNiuw7Ervsz93zsONoy7A8ouD-hG0f9VYWR2Rf4D9eIuyyuoWlTB8qhQJwEQRsuhuitXTCuGXy7CaAVrZcVGLJDHaxUYMOvn8Oxp1o6jtXoN6Rs6jkjE1aAWucQxoQBGvducnVJBCQAB3SIxHstviheyQ4RJwnix6sO7ADeAY1D4EhAWVVW_wuSw
